services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]

  user-service:
    build: { context: ., dockerfile: user-service/Dockerfile }
    depends_on: [kafka, postgres]
    environment:
      KAFKA_BROKERS: kafka:29092
      DB_URL: jdbc:postgresql://postgres:5432/app
      DB_USER: app
      DB_PASS: app
    ports: ["8081:8081"]

  order-service:
    build: { context: ., dockerfile: order-service/Dockerfile }
    depends_on: [kafka, postgres]
    environment:
      KAFKA_BROKERS: kafka:29092
      DB_URL: jdbc:postgresql://postgres:5432/app
      DB_USER: app
      DB_PASS: app
    ports: ["8082:8082"]

  notification-service:
    build: { context: ., dockerfile: notification-service/Dockerfile }
    depends_on: [kafka]
    environment:
      KAFKA_BROKERS: kafka:29092
    ports: ["8083:8083"]

  api-gateway:
    build: { context: ., dockerfile: api-gateway/Dockerfile }
    depends_on: [user-service, order-service, notification-service]
    environment:
      USER_SERVICE_URL: http://user-service:8081
      ORDER_SERVICE_URL: http://order-service:8082
      NOTIFICATION_SERVICE_URL: http://notification-service:8083
    ports: ["8080:8080"]

  prometheus:
    image: prom/prometheus:v2.54.1
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:11.2.0
    depends_on: [prometheus]
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    ports: ["3000:3000"]

volumes:
  pgdata:
